apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  DB_AUTO_UPDATE: "{{ .Values.config.DB_AUTO_UPDATE }}"
  DB_CREATE_TABLES: "{{ .Values.config.DB_CREATE_TABLES }}"
  DB_DATABASE: "{{ .Values.config.DB_NAME }}"
  DEBUG: "{{ .Values.config.DEBUG }}"
  MODULE_WEB_ADMIN: "{{ .Values.config.MODULE_WEB_ADMIN }}"
  OPENELIS_HOST: "{{ .Values.config.OPENELIS_HOST }}"
  OPENELIS_PORT: "{{ .Values.config.OPENELIS_PORT }}"
  MAIL_TRANSPORT_PROTOCOL: "{{ .Values.config.MAIL_TRANSPORT_PROTOCOL }}"
  MAIL_SMTP_AUTH: "{{ .Values.config.MAIL_SMTP_AUTH }}"
  MAIL_SMTP_STARTTLS_ENABLE: "{{ .Values.config.MAIL_SMTP_STARTTLS_ENABLE }}"
  MAIL_SMTP_SSL_ENABLE: "{{ .Values.config.MAIL_SMTP_SSL_ENABLE }}"
  MAIL_DEBUG: "{{ .Values.config.MAIL_DEBUG }}"
  SEND_MAIL: "{{ .Values.config.SEND_MAIL }}"
  MAIL_FROM: "{{ .Values.config.MAIL_FROM }}"
  MAIL_SMTP_PORT: "{{ .Values.config.MAIL_SMTP_PORT }}"
  MAIL_SMTP_HOST: "{{ .Values.config.MAIL_SMTP_HOST }}"
