apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  dbAutoUpdate: "{{ .Values.config.dbAutoUpdate }}"
  dbCreateTables: "{{ .Values.config.dbCreateTables }}"
  dbName: "{{ .Values.config.dbName }}"
  debug: "{{ .Values.config.debug }}"
  moduleWebAdmin: "{{ .Values.config.moduleWebAdmin }}"
  openELISHost: "{{ .Values.config.openELISHost }}"
  openELISPort: "{{ .Values.config.openELISPort }}"
