apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  OMRS_AUTO_UPDATE_DATABASE: "{{ .Values.config.OMRS_AUTO_UPDATE_DATABASE }}"
  OMRS_CREATE_TABLES: "{{ .Values.config.OMRS_CREATE_TABLES }}"
  OMRS_DB_NAME: "{{ .Values.config.OMRS_DB_NAME }}"
  OMRS_DEV_DEBUG_PORT: "{{ .Values.config.OMRS_DEV_DEBUG_PORT }}"
  OMRS_MODULE_WEB_ADMIN: "{{ .Values.config.OMRS_MODULE_WEB_ADMIN }}"
  OMRS_JAVA_SERVER_OPTS: "{{ .Values.config.OMRS_JAVA_SERVER_OPTS }}"
  OMRS_JAVA_MEMORY_OPTS: "{{ .Values.config.OMRS_JAVA_MEMORY_OPTS }}"
  OPENELIS_HOST: "{{ .Values.config.OPENELIS_HOST }}"
  OPENELIS_PORT: "{{ .Values.config.OPENELIS_PORT }}"
  MAIL_TRANSPORT_PROTOCOL: "{{ .Values.config.MAIL_TRANSPORT_PROTOCOL }}"
  MAIL_SMTP_AUTH: "{{ .Values.config.MAIL_SMTP_AUTH }}"
  MAIL_SMTP_STARTTLS_ENABLE: "{{ .Values.config.MAIL_SMTP_STARTTLS_ENABLE }}"
  MAIL_SMTP_SSL_ENABLE: "{{ .Values.config.MAIL_SMTP_SSL_ENABLE }}"
  MAIL_DEBUG: "{{ .Values.config.MAIL_DEBUG }}"
  SEND_MAIL: "{{ .Values.config.SEND_MAIL }}"
  MAIL_FROM: "{{ .Values.config.MAIL_FROM }}"
  MAIL_SMTP_PORT: "{{ .Values.config.MAIL_SMTP_PORT }}"
  MAIL_SMTP_HOST: "{{ .Values.config.MAIL_SMTP_HOST }}"
  OMRS_DOCKER_ENV: "{{ .Values.config.OMRS_DOCKER_ENV }}"
  TZ: "{{ .Values.global.TZ }}"
  OMRS_C3P0_MAX_SIZE: "{{ .Values.config.OMRS_C3P0_MAX_SIZE }}"
