apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: {{ .Values.metadata.labels.name }}
  name: {{ .Values.metadata.labels.name }}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.capacity }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openmrs-document-images-pv
spec:
  storageClassName: standard
  claimRef:
    name: {{ .Values.metadata.labels.name }}
  capacity:
    storage: {{ .Values.storage.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/Users/bahmni/openmrs-document-images'
