replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: bahmni
  name: openmrs-db
  tag: demo-latest

service:
  type: ClusterIP
  port: 3306

config:
  MYSQL_DATABASE: openmrs

secrets:
  MYSQL_USER: ""
  MYSQL_PASSWORD: ""
  MYSQL_ROOT_PASSWORD: ""


autoscaling:
  enabled: false
  #  minReplicas: 1
  #  maxReplicas: 5
  #  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
