name: Build and Upload OpenMRS Artifacts
on:
  push:
    branches:
      - BAH-2836
    
  workflow_dispatch:

jobs:
  build-upload-docker:
    name: Build & Upload
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/helm/openmrs
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
          ./mvnw --no-transfer-progress -U clean install
        env:
          USER_NAME: ${{ secrets.USERNAME }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: omods
          path: distro/